#!/bin/bash
#SBATCH -J revide_reduced_12_08_00
#SBATCH -o /scratch/08310/rs821505/train_outputs/full_runs/dehaze_reduced.o%j
#SBATCH -e /scratch/08310/rs821505/train_outputs/full_runs/dehaze_reduced.e%j
#SBATCH -p gpu-a100
#SBATCH -N 1
#SBATCH -n 128
#SBATCH -t 48:00:00

#SBATCH --mail-user=myemail@test.edu
#SBATCH --mail-type=begin        # email me when the job starts
#SBATCH --mail-type=end          # email me when the job finishes
module add gcc

python main.py --template Pre_Dehaze_revidereduced --prev_timestamp 20221208_00.14
python main.py --template Dehaze_revidereduced --auto_pre_train --prev_timestamp 20221208_00.14
